name: Invite to Organisation
on:
  push:
    branches: master
jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite the contributor to the organisation
        uses: lekterable/inclusive-organization-action@v1.1.0
        with:
          organization: LGBT-CN
          team: Friends
          comment: Thanks for your support❤
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
